x-default-logging: &default-logging
  logging:
    driver: json-file
    options:
      max-size: "100M"

services:
  server:
    image: judge0/judge0:1.13.1
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    tmpfs:
      - /sys/fs/cgroup:exec,mode=755
    ports:
      - "2358:2358"
    privileged: true
    cap_add:
      - SYS_ADMIN
    restart: always
    <<: *default-logging

  workers:
    image: judge0/judge0:1.13.1
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    tmpfs:
      - /sys/fs/cgroup:exec,mode=755
    privileged: true
    cap_add:
      - SYS_ADMIN
    restart: always
    <<: *default-logging

  db:
    image: postgres:16.2
    environment:
      POSTGRES_DB: judge0
      POSTGRES_USER: judge0
      POSTGRES_PASSWORD: zJJmL2RpQPPmqEdpbKTwqQcUjLQW8G6h
    volumes:
      - data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always

  redis:
    image: redis:7.2.4
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly no --requirepass "$${REDIS_PASSWORD}"'
    ]
    environment:
      REDIS_PASSWORD: 4R8KJTLnk62d7ZF4xLpSmMypPVJhUDGN
    <<: *default-logging
    restart: always

volumes:
  data:
